name: Test

on: push

jobs:
  install_specific_version:
    name: Install specific version of Jsonnet and print version
    runs-on: ubuntu-latest
    steps:
      - uses: zendesk/checkout@v2
      - uses: zendesk/setup-go@v2
        with:
          go-version: '^1.16.0' # Go >= 1.16 to have go install
      - name: Setup Jsonnet
        uses: ./
        with:
          version: v0.16.12
          github_token: ${{ github.token }}
      - name: Print Jsonnet version
        run: jsonnet -v
      - name: Print Jsonnet reformatter version
        run: jsonnetfmt -v

  install_latest:
    name: Install latest version of Jsonnet and print version
    runs-on: ubuntu-latest
    steps:
      - uses: zendesk/checkout@v2
      - uses: zendesk/setup-go@v2
        with:
          go-version: '^1.16.0' # Go >= 1.16 to have go install
      - name: Setup Jsonnet
        uses: ./
        with:
          github_token: ${{ github.token }}
      - name: Print Jsonnet version
        run: jsonnet -v
      - name: Print Jsonnet reformatter version
        run: jsonnetfmt -v
